### ISSUE TITLE
Use needle orientation protocol when calculating metrics

### ISSUE THREAD

**Issue by mholden8** [PerkTutor/PerkEvaluator#6]
Based on the discussion SlicerIGT/SlicerIGT#6, the needle metrics should be calculated assuming the needle follows the agreed upon needle orientation protocol.

**Comment by mholden8** [comment]
With the recent changes to the needle orientation protocol in SlicerIGT, the PerkEvaluator should be updated such that the default needle orientation is consistent with the SlicerIGT and PLUS needle orientation (see SlicerIGT/SlicerIGT#6).

Furthermore, all metrics should be updated such that they follow the user-specified needle orientation protocol, rather than just the default protocol. That is, all of the Python Metrics currently ignore the orientation selected in the GUI. These should be updated so that they use whatever protocol the user specifies with the GUI. 

This would make the PerkTutor still compatible with procedures that have been previously recorded using the old needle orientation protocol.

**Comment by matthewsholden** [comment]
Default needle orientation is indeed consistent with the SlicerIGT and PLUS needle orientations. There still is an advanced option to changes the needle orientation during metric calculation, for backwards compatibility with older recordings.
